### ISSUE TITLE
Plackett-Luce density bug?

### ISSUE THREAD

**Issue by jeffpollock9** [bob-carpenter/case-studies#1]
Hi @bob-carpenter, thanks for sharing these case studies.

I was wondering if perhaps there is a bug in https://github.com/bob-carpenter/case-studies/blob/master/sushi-rating/plackett-luce.stan#L4:

``` stan 
return sum(log(beta_y ./ cumulative_sum(beta_y)));
```

or maybe just my misunderstanding of how you have arranged the data or something. I would expected to see the cumulative sum be reversed since e.g. if `beta_y[1]` is the parameter for the best sushi  and `beta_y` has size 3 then I think the denominators should be:

``` stan
beta_y[1] + beta_y[2] + beta_y[3]
beta_y[2] + beta_y[3]
beta_y[3]
```

but the current code looks to me to give:

``` stan
beta_y[1] 
beta_y[1] + beta_y[2]
beta_y[1] + beta_y[2] + beta_y[3]
```

Looking at other implementations seems to have some sort of reversing, e.g. [TensorFlow Probability](https://github.com/tensorflow/probability/blob/65f265c62bb1e2d15ef3e25104afb245a6d52429/tensorflow_probability/python/distributions/plackett_luce.py#L230).

Thanks!

**Comment by bob-carpenter** [comment]
Thanks for the feedback.

I just assumed the data was coming in decreasing rather than increasing order to simplify the Stan code.  But then I never changed the doc on the data variable. 

I'm always harping on about how doc can be misleading because it gets out of synch with the code.  I should've called `y` either `y_increasing` or `y_decreasing` and then I would've noticed to change the variable name as I went along.

**Comment by jeffpollock9** [comment]
@bob-carpenter thanks!
